### ISSUE TITLE
Create a better UX for input

### ISSUE THREAD

**Issue by caprius** [danmedani/pager_duty_stats#18]
CLI input is pretty tedious!  Let's think about a GUI with drop-downs.

**Comment by danmedani** [comment]
Ideas for displaying charts:

- https://canvasjs.com/javascript-charts/stacked-column-chart/
- https://www.syncfusion.com/javascript-ui-controls/js-charts/chart-types/stacked-column-chart
- https://apexcharts.com/javascript-chart-demos/column-charts/stacked/
- https://www.chartjs.org/
